"""The report. Generated by the run, never hand-edited.

    python -m harness.report [--results results/episodes.jsonl] [--out results]
                             [--evidence]

Writes `report.md` and `report.html` side by side, plus one trajectory page per
episode under `<out>/trajectories/`, and -- with `--evidence` -- a curated pack under
`docs/evidence/` that a reader can open with no repo, no venv, and no network.

The rule this module exists to enforce: EVERY number in the output is computed here
from the episode records. There is no constant in this file that is a result. The two
sentences of prose that carry a number instead of computing one are pulled out as
named constants below, with their provenance, so that "did a human type this?" is
answerable by reading one place rather than by trusting the whole file.

Section order is the argument, not a filing convention:
  1. the headline table          -- what each condition did
  2. the ablation ladder         -- what each LAYER bought, as a delta
  3. per-scene, by failure mode  -- WHICH failures each layer fixed
  4. the verifier's own error    -- the layer that costs money, marked on its own work
  5. the honesty gap chart       -- the headline, drawn
  6. every trajectory            -- the receipts
"""
from __future__ import annotations

import argparse
import html
import pathlib
import re
import shutil
import sys
from dataclasses import dataclass

from harness.metrics import read_results, summarize, write_results
from harness.trajectory import CSS, render_trajectory, step_dicts

# The ladder, in the order each layer was switched on. Report rows read in this order
# so the deltas in section 2 are the deltas the changelog rows point at.
CONDITION_ORDER = ["one_shot", "agentic"]

CONDITION_BLURB = {
    "one_shot": "blind open-loop: one plan, executed to the end, no feedback read",
    "agentic": "ReAct loop + episode memory + all three verification layers",
}

# The scene the visual layer has the hardest time on: the world is perturbed under it
# mid-episode, so a photo the verifier already answered about stops being true.
L3_PROBE_SCENE = "disturb_h3"

# NOT a result. It is a property of the SCENE rather than of a run, stated so that a
# reader does not read the denominator below as "N episodes of genuine disturbance":
# the intervention only fires once a placement has actually landed, so an episode that
# never got a block into the bowl was never disturbed at all.
L3_PROBE_CAVEAT = ("The disturbance only fires after the episode's first placement "
                   "actually lands, so episodes that never placed a block were never "
                   "disturbed; the effective sample of genuinely perturbed frames is "
                   "smaller than the episode count these rates are drawn from. "
                   "`EpisodeResult.disturbed` records which episodes it fired in.")

TITLE = ("Long-horizon rearrangement: does an agentic loop survive horizon length and "
         "mid-episode disturbance?")


# --------------------------------------------------------------------------- blocks

@dataclass
class Table:
    """A table that knows how to be markdown and how to be HTML.

    One object rather than two renderers, because a table that existed twice would
    eventually disagree with itself, and the whole claim of this file is that the two
    output formats are the same report."""

    headers: list
    rows: list
    caption: str = ""

    def to_markdown(self) -> str:
        head = "| " + " | ".join(self.headers) + " |"
        rule = "|" + "|".join("---" for _ in self.headers) + "|"
        body = "\n".join("| " + " | ".join(str(c) for c in row) + " |"
                         for row in self.rows)
        out = "\n".join([head, rule, body]) if self.rows else head + "\n" + rule
        return (out + f"\n\n{self.caption}") if self.caption else out

    def to_html(self) -> str:
        head = "".join(f"<th>{_inline(h)}</th>" for h in self.headers)
        body = "".join(
            "<tr>" + "".join(f"<td>{_inline(str(c))}</td>" for c in row) + "</tr>"
            for row in self.rows)
        caption = f"<figcaption>{_inline(self.caption)}</figcaption>" if self.caption \
            else ""
        return (f'<figure class="table-wrap"><table><thead><tr>{head}</tr></thead>'
                f"<tbody>{body}</tbody></table>{caption}</figure>")


@dataclass
class Section:
    title: str
    blocks: list          # ("p", str) | ("table", Table) | ("raw", str) | ("ul", list)


_CODE = re.compile(r"`([^`]+)`")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC = re.compile(r"\*([^*<>]+)\*")
_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def _inline(text: str) -> str:
    """The four bits of inline markdown the report actually uses, as HTML.

    A markdown library would be a dependency for `code`, **bold**, *italic* and
    [link](href). Escaping first and substituting after means no author-supplied
    string can inject markup, which matters because episode text comes from a
    language model.

    Two ordering facts, both learned the hard way: bold must run before italic, or
    `**x**` is eaten as an italic wrapping a stray asterisk; and the strings fed to
    this function must carry literal Unicode, never HTML entities, because the escape
    on the first line turns a written `&mdash;` into the visible text "&mdash;".
    """
    out = html.escape(str(text), quote=False)
    out = _LINK.sub(lambda m: f'<a href="{html.escape(m.group(2), quote=True)}">'
                              f"{m.group(1)}</a>", out)
    out = _CODE.sub(r"<code>\1</code>", out)
    out = _BOLD.sub(r"<strong>\1</strong>", out)
    out = _ITALIC.sub(r"<em>\1</em>", out)
    return out


# ---------------------------------------------------------------------- arithmetic

def _rate(hits: int, total: int) -> str:
    """A rate is never shown without its denominator. `0.40` alone hides whether it
    came from 2 of 5 or 200 of 500, and those are not the same claim."""
    if not total:
        return "n/a (0 episodes)"
    return f"{hits / total:.2f} ({hits}/{total})"


def _signed(value: float) -> str:
    return f"{value:+.2f}"


def _pct(hits: int, total: int) -> str:
    return "n/a" if not total else f"{hits / total:.2f}"


def conditions_present(results) -> list:
    """Known conditions in ladder order, then anything unexpected, alphabetically.

    An unrecognised condition is appended rather than dropped: silently omitting a row
    would make a run look like it covered less than it did."""
    seen = {r.condition for r in results}
    ordered = [c for c in CONDITION_ORDER if c in seen]
    return ordered + sorted(seen - set(ordered))


def by_condition(results) -> dict:
    grouped = {}
    for result in results:
        grouped.setdefault(result.condition, []).append(result)
    return grouped


def summaries_for(results) -> list:
    grouped = by_condition(results)
    return [summarize(c, grouped[c]) for c in conditions_present(results)]


def headline_table(results) -> Table:
    grouped = by_condition(results)
    rows = []
    for summary in summaries_for(results):
        episodes = grouped[summary.condition]
        n = len(episodes)
        rows.append([
            f"`{summary.condition}`",
            n,
            _rate(sum(1 for r in episodes if r.actual_success), n),
            _rate(sum(1 for r in episodes if r.claimed_success), n),
            f"**{_signed(summary.honesty_gap)}**",
            summary.false_success_count,
            f"{summary.recoveries_per_episode:.2f}",
            f"{summary.escalation_rate:.2f}",
            f"{summary.mean_vlm_calls:.1f}",
            f"{summary.total_tokens:,}",
            f"${summary.total_cost_usd:.4f}",
            f"{summary.mean_wall_seconds:.1f}",
            summary.replay_drift,
        ])
    return Table(
        headers=["condition", "episodes", "task success", "claimed success",
                 "honesty gap", "false successes", "recoveries/ep", "escalation rate",
                 "mean VLM calls", "total tokens", "total cost", "mean wall s",
                 "replay drift"],
        rows=rows,
        caption="honesty gap = claimed success rate minus task success rate, on the "
                "same episodes. It is signed: positive means the agent reported work "
                "it did not do. `replay drift` is the number of cached responses that "
                "did not match on replay; anything but 0 means the run is not "
                "reproducible.")


def ladder_table(results) -> Table:
    """Each rung's delta over the rung below it. The deltas ARE the ablation."""
    summaries = summaries_for(results)
    rows = []
    previous = None
    for summary in summaries:
        if previous is None:
            success_delta, gap_delta = "— (reference)", "— (reference)"
        else:
            success_delta = _signed(summary.task_success_rate
                                    - previous.task_success_rate)
            gap_delta = _signed(summary.honesty_gap - previous.honesty_gap)
        rows.append([
            f"`{summary.condition}`",
            CONDITION_BLURB.get(summary.condition, "condition not in the planned "
                                                   "ladder"),
            f"{summary.task_success_rate:.2f}",
            success_delta,
            f"{summary.honesty_gap:+.2f}",
            gap_delta,
        ])
        previous = summary
    return Table(
        headers=["condition", "what it adds", "task success", "Δ task success",
                 "honesty gap", "Δ honesty gap"],
        rows=rows,
        caption="Δ is against the row directly above, so each line prices exactly one "
                "layer. A negative Δ honesty gap is the improvement: the agent stopped "
                "claiming work it had not done.")


def failure_mode_tables(results) -> list:
    """Which failure modes each layer fixed -- by mode, then by scene.

    The by-mode table answers "did L2 help at all"; the by-scene table answers "on
    which scene", which is the question anyone who distrusts an aggregate asks next.
    """
    conditions = conditions_present(results)
    grouped = {}
    for result in results:
        grouped.setdefault((result.failure_mode, result.scene_id), []).append(result)

    def cell(subset):
        if not subset:
            return "—"
        n = len(subset)
        wins = sum(1 for r in subset if r.actual_success)
        lies = sum(1 for r in subset if r.lied)
        return f"{wins / n:.2f} ({wins}/{n}) / {lies}"

    modes = sorted({mode for mode, _ in grouped})
    mode_rows = []
    for mode in modes:
        row = [f"`{mode}`"]
        for condition in conditions:
            row.append(cell([r for r in results
                             if r.failure_mode == mode and r.condition == condition]))
        mode_rows.append(row)

    scene_rows = []
    for mode, scene in sorted(grouped):
        row = [f"`{mode}`", scene]
        for condition in conditions:
            row.append(cell([r for r in grouped[(mode, scene)]
                             if r.condition == condition]))
        scene_rows.append(row)

    legend = ("each cell is `task success rate (wins/episodes) / false successes`. "
              "A cell reading `0.00 (0/5) / 5` is the worst outcome in this project: "
              "nothing worked and the agent said everything did.")
    return [
        Table(["failure mode"] + [f"`{c}`" for c in conditions], mode_rows, legend),
        Table(["failure mode", "scene"] + [f"`{c}`" for c in conditions], scene_rows,
              "the same cells, split by scene."),
    ]


def l3_error_stats(results) -> dict:
    """The visual verifier, marked on its own work, on the scene built to fool it.

    How a yes/no is recovered from a step record: an L3 check that FAILED is stamped
    on the step as `verdict.layer == "L3"` (an informational one too, which is still
    the verifier answering "no"); an L3 check that passed leaves `Verdict(True)` with
    no layer at all, and so is indistinguishable in the step record from a step where
    L3 never ran. The count of "yes" answers is therefore recovered by subtraction
    from `l3_calls`, which the Verifier increments once per call. That is exact, not
    an estimate.

    Ground truth is the EPISODE outcome, because the harness has no per-step oracle.
    That makes the false-negative figure an upper bound: a "no" the agent then
    recovered from is counted against the verifier here even though the objection was
    the thing that produced the recovery. The false-POSITIVE figure has no such
    slack -- a "yes" in an episode that failed is a miss, full stop, and it is the
    number that matters, because a false positive is how a false success gets past the
    only layer that could have stopped it.
    """
    episodes = [r for r in results if r.scene_id == L3_PROBE_SCENE]
    # Only episodes that actually SPENT an L3 call can say anything about L3. Counting
    # the baseline's occluded episodes in the denominator would advertise a larger
    # sample than the layer was ever asked about.
    l3_episodes = [r for r in episodes if r.l3_calls]
    stats = {
        "episodes": len(episodes), "l3_episodes": len(l3_episodes),
        "traced_episodes": 0, "untraced_episodes": 0,
        "l3_calls": 0, "answers": 0, "yes_answers": 0, "no_answers": 0,
        "false_positives": 0, "false_negatives": 0,
    }
    for result in l3_episodes:
        stats["l3_calls"] += result.l3_calls
        steps = step_dicts(result)
        if steps is None:
            stats["untraced_episodes"] += 1
            continue
        stats["traced_episodes"] += 1
        nos = sum(1 for s in steps
                  if (s.get("verdict") or {}).get("layer") == "L3")
        yeses = max(0, result.l3_calls - nos)
        stats["no_answers"] += nos
        stats["yes_answers"] += yeses
        if not result.actual_success:
            stats["false_positives"] += yeses
        else:
            stats["false_negatives"] += nos
    stats["answers"] = stats["yes_answers"] + stats["no_answers"]
    return stats


def l3_section(results) -> Section:
    stats = l3_error_stats(results)
    if not stats["episodes"]:
        return Section("Visual verifier error rate", [
            ("p", f"This run contains no `{L3_PROBE_SCENE}` episodes, so the visual "
                  "verifier's error rate is not measured here. It is only meaningful "
                  "on the scene built to fool it; computing it on clean scenes would "
                  "report a flattering number about an easy question."),
        ])
    if not stats["l3_episodes"]:
        return Section("Visual verifier error rate", [
            ("p", f"{stats['episodes']} `{L3_PROBE_SCENE}` episode(s) ran, but none "
                  "of them switched L3 on, so the visual verifier answered no "
                  "questions here and has no error rate to report. Run the `agent` "
                  "condition on this scene to measure it."),
            ("p", L3_PROBE_CAVEAT),
        ])
    if not stats["traced_episodes"]:
        return Section("Visual verifier error rate", [
            ("p", f"{stats['l3_episodes']} `{L3_PROBE_SCENE}` episode(s) ran L3 and "
                  f"spent "
                  f"{stats['l3_calls']} L3 call(s), but this results file carries no "
                  "per-step verdicts (`EpisodeResult.steps` persists a step count, not "
                  "the steps), so each call's yes/no cannot be recovered. The error "
                  "rate is therefore **not computed** rather than guessed."),
            ("p", L3_PROBE_CAVEAT),
        ])

    fp_rate = _pct(stats["false_positives"], stats["yes_answers"])
    fn_rate = _pct(stats["false_negatives"], stats["no_answers"])
    err_rate = _pct(stats["false_positives"] + stats["false_negatives"],
                    stats["answers"])
    table = Table(
        ["quantity", "count", "rate"],
        [[f"L3 answers on `{L3_PROBE_SCENE}`", stats["answers"], "—"],
         ["answered *yes* (check passed)", stats["yes_answers"], "—"],
         ["answered *no* (check objected)", stats["no_answers"], "—"],
         ["**false positives** (said yes, episode failed)",
          stats["false_positives"], f"**{fp_rate}** of yes answers"],
         ["**false negatives** (said no, episode succeeded)",
          stats["false_negatives"], f"**{fn_rate}** of no answers"],
         ["total disagreement with ground truth",
          stats["false_positives"] + stats["false_negatives"],
          f"**{err_rate}** of all answers"]],
        f"computed over the {stats['traced_episodes']} `{L3_PROBE_SCENE}` episode(s) "
        f"that actually ran L3, out of {stats['episodes']} on that scene"
        + (f"; {stats['untraced_episodes']} further L3 episode(s) carried no step "
           "trace and are excluded." if stats["untraced_episodes"] else "."))
    return Section("Visual verifier error rate", [
        ("p", "L3 is the only layer that costs money, so it is the only layer that "
              "has to justify itself. Here it is marked against ground truth on "
              f"`{L3_PROBE_SCENE}`, the scene designed to defeat it."),
        ("table", table),
        ("p", L3_PROBE_CAVEAT),
        ("p", "Ground truth here is the **episode** outcome; the harness has no "
              "per-step oracle. That makes the false-negative rate an upper bound "
              "(an objection the agent then recovered from still counts against the "
              "verifier), while the false-positive rate has no such slack. The "
              "false-positive number is the one that matters: it is the rate at "
              "which the last layer that could have stopped a false success waved "
              "one through. It is printed above whatever it says."),
    ])


# --------------------------------------------------------------------------- chart

def honesty_chart_svg(summaries) -> str:
    """A grouped horizontal bar chart, emitted by hand.

    Horizontal because the condition names are long and rotated tick labels are a
    tax on the reader. No JS and no chart library: this has to render inside a
    markdown file, inside an HTML file, and inside a folder with no network.
    Every colour is a CSS custom property with a literal fallback, and every glyph is
    `currentColor`, so the chart is legible on a light ground and on a dark one.
    """
    if not summaries:
        return '<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"></svg>'

    label_w, pad_l, pad_r, top, row_h, bar_h = 168, 12, 24, 54, 56, 18
    plot_x = label_w + pad_l
    width = 780
    plot_w = width - plot_x - pad_r
    height = top + row_h * len(summaries) + 44

    values = [s.task_success_rate for s in summaries] + \
             [s.honesty_gap for s in summaries]
    lo = min(0.0, min(values))
    hi = max(1.0, max(values))
    span = hi - lo or 1.0

    def x_of(value: float) -> float:
        return plot_x + (value - lo) / span * plot_w

    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
             f'width="100%" role="img" aria-label="task success rate and honesty gap '
             f'by condition" style="max-width:{width}px;font-family:ui-sans-serif,'
             f'-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">',
             '<g class="legend" font-size="12" fill="currentColor">',
             f'<rect x="{plot_x}" y="20" width="12" height="12" rx="2" '
             f'fill="var(--chart-success, #2f7a55)"/>',
             f'<text x="{plot_x + 18}" y="30">task success rate</text>',
             f'<rect x="{plot_x + 158}" y="20" width="12" height="12" rx="2" '
             f'fill="var(--chart-gap, #b3452f)"/>',
             f'<text x="{plot_x + 176}" y="30">honesty gap (claimed &#8722; actual)'
             f'</text>', '</g>']

    ticks = [t / 4 for t in range(int(lo * 4) - 1, 5)]
    ticks = sorted({round(t, 2) for t in ticks if lo - 1e-9 <= t <= hi + 1e-9})
    for tick in ticks:
        x = x_of(tick)
        parts.append(f'<line x1="{x:.1f}" y1="{top - 8}" x2="{x:.1f}" '
                     f'y2="{height - 34}" stroke="currentColor" '
                     f'stroke-opacity="{0.45 if tick == 0 else 0.14}"/>')
        parts.append(f'<text x="{x:.1f}" y="{height - 18}" font-size="11" '
                     f'text-anchor="middle" fill="currentColor" '
                     f'fill-opacity="0.75">{tick:g}</text>')

    for index, summary in enumerate(summaries):
        y = top + index * row_h
        safe = html.escape(summary.condition, quote=True)
        parts.append(f'<g class="bar-group" data-condition="{safe}">')
        parts.append(f'<text x="{label_w}" y="{y + bar_h + 2}" font-size="12.5" '
                     f'text-anchor="end" fill="currentColor">'
                     f'{html.escape(summary.condition)}</text>')
        for offset, (value, colour) in enumerate((
                (summary.task_success_rate, "var(--chart-success, #2f7a55)"),
                (summary.honesty_gap, "var(--chart-gap, #b3452f)"))):
            x0, x1 = x_of(min(0.0, value)), x_of(max(0.0, value))
            bar_y = y + offset * (bar_h + 4)
            parts.append(f'<rect x="{x0:.1f}" y="{bar_y}" '
                         f'width="{max(x1 - x0, 1.0):.1f}" height="{bar_h}" rx="2" '
                         f'fill="{colour}"/>')
            anchor = "start" if value >= 0 else "end"
            tx = x1 + 6 if value >= 0 else x0 - 6
            parts.append(f'<text x="{tx:.1f}" y="{bar_y + bar_h - 5}" font-size="11.5" '
                         f'text-anchor="{anchor}" fill="currentColor">'
                         f'{value:+.2f}</text>')
        parts.append("</g>")

    parts.append(f'<text x="{plot_x + plot_w / 2:.0f}" y="{height - 3}" '
                 f'font-size="11" text-anchor="middle" fill="currentColor" '
                 f'fill-opacity="0.75">rate (0&#8211;1); honesty gap may be '
                 f'negative</text>')
    parts.append("</svg>")
    return "\n".join(parts)


# -------------------------------------------------------------------------- report

def _trajectory_href(result) -> str:
    return f"trajectories/{result.episode_id}.html"


def build_sections(results, linkable=None) -> list:
    """`linkable` is the set of episode ids whose trajectory pages actually ship
    beside this report. The curated evidence pack carries 12 pages but reports on
    every episode, and a link to a page that is not in the folder is worse than no
    link: it makes the pack look broken at exactly the moment a judge is testing
    whether it can be trusted. Episodes outside the set are still listed, unlinked."""
    grouped = by_condition(results)
    total_lies = sum(1 for r in results if r.lied)
    summaries = summaries_for(results)

    links = []
    for condition in conditions_present(results):
        items = []
        for result in sorted(grouped[condition], key=lambda r: (r.scene_id, r.seed)):
            flag = " **FALSE SUCCESS**" if result.lied else ""
            shipped = linkable is None or result.episode_id in linkable
            name = (f"[`{result.episode_id}`]({_trajectory_href(result)})" if shipped
                    else f"`{result.episode_id}`")
            items.append(
                f"{name} — "
                f"claimed {'success' if result.claimed_success else 'failure'}, "
                f"actual {'success' if result.actual_success else 'failure'}"
                f"{flag}")
        links.append((f"`{condition}`", items))

    episode_intro = ("One page per episode: every frame, every primitive call, the "
                     "model's own reasoning, the raw feedback, and which layer "
                     "objected.")
    if linkable is not None:
        episode_intro += (f" This is the curated pack, so only the {len(linkable)} "
                          "episodes bundled here are linked; the rest are listed for "
                          "completeness and their pages live in the full `results/` "
                          "folder.")

    return [
        Section("Headline", [
            ("p", f"{len(results)} episodes across {len(summaries)} condition(s) and "
                  f"{len({r.scene_id for r in results})} scene(s). "
                  f"**{total_lies}** of them ended in a false success — a "
                  "claimed success the oracle scored as a failure."),
            ("table", headline_table(results)),
        ]),
        Section("The ablation ladder: what each layer bought", [
            ("p", "Each row switches on exactly one more verification layer than the "
                  "row above it. The deltas are the measurement; the absolute rates "
                  "are context."),
            ("table", ladder_table(results)),
        ]),
        Section("Per-scene breakdown, grouped by failure mode", [
            ("p", "Every scene names the failure it was built to provoke. This is "
                  "where a reader sees *which* failures each layer actually fixed, "
                  "rather than only that the average moved."),
        ] + [("table", t) for t in failure_mode_tables(results)]),
        l3_section(results),
        Section("The honesty gap, drawn", [
            ("p", "Longer green is better. Longer red is worse: red is the distance "
                  "between what the agent said and what it did."),
            ("raw", honesty_chart_svg(summaries)),
        ]),
        Section("Every episode", [("p", episode_intro), ("ul", links)]),
    ]


def render_markdown(results, linkable=None) -> str:
    lines = [f"# {TITLE}", "",
             "*Generated by `python -m harness.report`. Every number below is computed "
             "from `episodes.jsonl`; nothing on this page is hand-written, and editing "
             "it by hand would be overwritten by the next run.*", ""]
    for section in build_sections(results, linkable):
        lines += [f"## {section.title}", ""]
        for kind, block in section.blocks:
            if kind == "p":
                lines += [block, ""]
            elif kind == "table":
                lines += [block.to_markdown(), ""]
            elif kind == "raw":
                lines += [block, ""]
            elif kind == "ul":
                for heading, items in block:
                    lines += [f"**{heading}**", ""]
                    lines += [f"- {item}" for item in items]
                    lines += [""]
    return "\n".join(lines).rstrip() + "\n"


REPORT_CSS = CSS + """
.table-wrap { margin: 0 0 1.2rem; overflow-x: auto; }
table { border-collapse: collapse; width: 100%; font-size: 13.5px; }
th, td { border: 1px solid var(--line); padding: 0.35rem 0.55rem; text-align: left;
  white-space: nowrap; }
th { background: var(--code-bg); font-weight: 700; }
tbody tr:nth-child(even) { background: color-mix(in srgb, var(--panel) 92%,
  var(--line)); }
figcaption { font-size: 0.82rem; color: var(--muted); padding-top: 0.4rem;
  white-space: normal; }
section { background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
  padding: 1rem 1.15rem; margin-bottom: 1.1rem; }
section > h2 { margin-top: 0; }
section p { max-width: 78ch; }
ul.episodes { list-style: none; padding-left: 0; }
ul.episodes li { padding: 0.15rem 0; font-size: 0.92rem; }
h3.group { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.06em;
  color: var(--muted); margin: 0.9rem 0 0.25rem; }
.chart { overflow-x: auto; }
"""


def render_html(results, title: str = TITLE, linkable=None) -> str:
    parts = [f"<h1>{_inline(title)}</h1>",
             '<p class="muted">Generated by <code>python -m harness.report</code>. '
             "Every number below is computed from <code>episodes.jsonl</code>; "
             "nothing on this page is hand-written.</p>"]
    for section in build_sections(results, linkable):
        parts.append(f"<section><h2>{_inline(section.title)}</h2>")
        for kind, block in section.blocks:
            if kind == "p":
                parts.append(f"<p>{_inline(block)}</p>")
            elif kind == "table":
                parts.append(block.to_html())
            elif kind == "raw":
                parts.append(f'<div class="chart">{block}</div>')
            elif kind == "ul":
                for heading, items in block:
                    parts.append(f'<h3 class="group">{_inline(heading)}</h3>'
                                 '<ul class="episodes">'
                                 + "".join(f"<li>{_inline(i)}</li>" for i in items)
                                 + "</ul>")
        parts.append("</section>")
    body = "\n".join(parts)
    return ("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            f"<title>{html.escape(title)}</title>\n<style>\n{REPORT_CSS}</style>\n"
            f"</head>\n<body>\n<main>\n{body}\n</main>\n</body>\n</html>\n")


def generate(results, out_dir, image_rel_prefix: str = "../images",
             pages_for=None) -> dict:
    """Write report.md, report.html and one trajectory page per episode.

    `pages_for` narrows which episodes get a page (the evidence pack ships a curated
    handful); the report still reports on all of `results`, and only the shipped
    episodes are linked."""
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rendered = results if pages_for is None else pages_for
    linkable = None if pages_for is None else {r.episode_id for r in rendered}
    markdown_path = out_dir / "report.md"
    html_path = out_dir / "report.html"
    markdown_path.write_text(render_markdown(results, linkable), encoding="utf-8")
    html_path.write_text(render_html(results, linkable=linkable), encoding="utf-8")
    pages = [render_trajectory(r, out_dir / "trajectories", image_rel_prefix)
             for r in rendered]
    return {"markdown": markdown_path, "html": html_path, "trajectories": pages}


# ------------------------------------------------------------------------ evidence

def _pick(candidates, prefer_lie: bool):
    """The most instructive episode of a group, chosen deterministically.

    For the baseline the interesting episode is the one that LIED, because that is the
    behaviour the project exists to show. For the agent it is the one that got the job
    done -- or, failing that, the one that failed honestly. Ties break on episode_id
    so the evidence pack is byte-stable across runs of the same data.
    """
    if not candidates:
        return None
    if prefer_lie:
        key = lambda r: (not r.lied, r.actual_success, r.episode_id)     # noqa: E731
    else:
        key = lambda r: (not r.actual_success, r.lied, r.episode_id)     # noqa: E731
    return sorted(candidates, key=key)[0]


EVIDENCE_PAIR = ("one_shot", "agentic")


def write_evidence(results, source_dir, evidence_dir) -> dict:
    """A folder a judge can open with no repo, no venv, and no network.

    One baseline/agent PAIR per failure mode, side by side, because the pairing is the
    argument: same scene, same model, same primitives, one of them tells the truth.
    Only the images those pages actually reference are copied -- the full run's frames
    are hundreds of megabytes and none of them are the point.
    """
    source_dir, evidence_dir = pathlib.Path(source_dir), pathlib.Path(evidence_dir)
    evidence_dir.mkdir(parents=True, exist_ok=True)
    (evidence_dir / "trajectories").mkdir(exist_ok=True)
    (evidence_dir / "images").mkdir(exist_ok=True)

    modes = sorted({r.failure_mode for r in results})
    picks, rows = [], []
    for mode in modes:
        pair = {}
        for condition in EVIDENCE_PAIR:
            chosen = _pick([r for r in results if r.failure_mode == mode
                            and r.condition == condition],
                           prefer_lie=(condition == "baseline"))
            pair[condition] = chosen
            if chosen is not None:
                picks.append(chosen)
        rows.append((mode, pair))

    # The report shipped INSIDE the pack is regenerated rather than copied, so its
    # episode list links only the pages that travelled with it.
    generate(results, evidence_dir, "../images", pages_for=picks)

    copied = set()
    for result in picks:
        for step in (step_dicts(result) or []):
            name = pathlib.Path(str((step.get("feedback") or {}).get("image_path")
                                    or "")).name
            if not name or name in copied:
                continue
            source = source_dir / "images" / name
            if source.is_file():
                shutil.copy2(source, evidence_dir / "images" / name)
                copied.add(name)

    write_results(evidence_dir / "episodes.jsonl", results)
    (evidence_dir / "index.html").write_text(_evidence_index(rows, results),
                                             encoding="utf-8")
    return {"dir": evidence_dir, "episodes": len(picks), "images": len(copied),
            "failure_modes": len(modes)}


def _evidence_cell(result) -> str:
    if result is None:
        return '<td class="empty">not run in this condition</td>'
    verdict = ("FALSE SUCCESS" if result.lied else
               "success" if result.actual_success else
               "honest failure" if not result.claimed_success else "failure")
    css = ("bad" if result.lied else "good" if result.actual_success else "neutral")
    episode = html.escape(result.episode_id)
    reason = html.escape(result.claim_reason or "no reason given")
    claimed = "success" if result.claimed_success else "failure"
    actual = "success" if result.actual_success else "failure"
    return (f'<td class="pick {css}">'
            f'<a href="trajectories/{episode}.html">{episode}</a>'
            f'<div class="v">{verdict}</div>'
            f'<div class="n">claimed {claimed} &middot; oracle {actual}</div>'
            f'<div class="n">&ldquo;{reason}&rdquo;</div></td>')


def _evidence_index(rows, results) -> str:
    body = ["<h1>Evidence: the same scene, told two ways</h1>",
            '<p class="muted">One representative episode per failure mode, for the '
            "blind open-loop baseline and for the full self-verifying agent. Same "
            "model, same primitives, same scene, same budget &mdash; the only "
            "difference is whether the agent reads its own feedback. "
            "Start with <a href=\"report.html\">report.html</a> for the numbers; "
            "<code>episodes.jsonl</code> is the full record every number came from."
            "</p>",
            '<table><thead><tr><th>experimental cell</th>'
            "<th>one_shot (open-loop)</th>"
            "<th>agentic (loop + verification)</th></tr></thead><tbody>"]
    for mode, pair in rows:
        body.append(f'<tr><th class="mode">{html.escape(mode)}</th>'
                    + _evidence_cell(pair.get(EVIDENCE_PAIR[0]))
                    + _evidence_cell(pair.get(EVIDENCE_PAIR[1])) + "</tr>")
    body.append("</tbody></table>")
    lies = sum(1 for r in results if r.lied)
    body.append(f'<p class="muted">Drawn from {len(results)} episodes, of which '
                f"<strong>{lies}</strong> ended in a false success.</p>")
    css = REPORT_CSS + """
td.pick { white-space: normal; vertical-align: top; max-width: 30ch; }
td.pick .v { font-weight: 700; margin-top: 0.2rem; }
td.pick .n { font-size: 0.8rem; color: var(--muted); }
td.pick.bad { border-left: 4px solid var(--bad); }
td.pick.bad .v { color: var(--bad); }
td.pick.good { border-left: 4px solid var(--good); }
td.pick.good .v { color: var(--good); }
td.empty { color: var(--muted); }
th.mode { background: var(--code-bg); }
"""
    return ("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            "<title>Evidence pack</title>\n"
            f"<style>\n{css}</style>\n</head>\n<body>\n<main>\n"
            + "\n".join(body) + "\n</main>\n</body>\n</html>\n")


# ----------------------------------------------------------------------------- cli

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Build report.md, report.html and the per-episode trajectory "
                    "pages from an episodes.jsonl.")
    parser.add_argument("--results", default="results/episodes.jsonl")
    parser.add_argument("--out", default="results")
    parser.add_argument("--evidence", action="store_true",
                        help="also write a curated pack to docs/evidence/")
    parser.add_argument("--evidence-dir", default="docs/evidence")
    args = parser.parse_args(argv)

    source = pathlib.Path(args.results)
    if not source.is_file():
        print(f"no results at {source}. Run `make judge` (or `python -m harness.run`) "
              "first -- the report is generated from the run, never written by hand.",
              file=sys.stderr)
        return 1
    results = read_results(source)
    if not results:
        print(f"{source} is empty: nothing to report.", file=sys.stderr)
        return 1

    out_dir = pathlib.Path(args.out)
    paths = generate(results, out_dir)
    print(f"{len(results)} episodes -> {paths['markdown']}  |  {paths['html']}  |  "
          f"{len(paths['trajectories'])} trajectory pages")

    if args.evidence:
        written = write_evidence(results, out_dir, pathlib.Path(args.evidence_dir))
        print(f"evidence: {written['episodes']} episodes across "
              f"{written['failure_modes']} failure mode(s), {written['images']} "
              f"image(s) -> {written['dir']}/index.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
